### ISSUE TITLE
i get this error log in notepad++ plugin

### ISSUE THREAD

**Issue by Abhay112233** [wakatime/notepadpp-wakatime#1]
13:57:38 : WakaTime : ERROR : An exception occured : The remote name could not be resolved: 'www.python.org'
13:57:41 : WakaTime : ERROR : Could not send heartbeat :  "C:\Users\KJ\AppData\Roaming\Notepad++\plugins\Config\wakatime-master\wakatime\cli.py" --key="" --file="new  0" --plugin="notepadpp/393293 notepadpp-wakatime/1.0.0"
13:57:41 : WakaTime : ERROR : Could not send heartbeat : Cannot start process because a file name has not been provided.
14:17:05 : WakaTime : ERROR : An exception occured : Could not load file or assembly 'System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
14:17:09 : WakaTime : ERROR : Could not send heartbeat :  "C:\Users\KJ\AppData\Roaming\Notepad++\plugins\Config\wakatime-master\wakatime\cli.py" --key="" --file="new  0" --plugin="notepadpp/393293 notepadpp-wakatime/1.0.0"
14:17:09 : WakaTime : ERROR : Could not send heartbeat : Cannot start process because a file name has not been provided.
14:21:12 : WakaTime : ERROR : An exception occured : Could not load file or assembly 'System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
14:21:19 : WakaTime : ERROR : An exception occured : Could not load file or assembly 'System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
14:25:00 : WakaTime : ERROR : An exception occured : Could not load file or assembly 'System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
15:52:34 : WakaTime : ERROR : An exception occured : Could not load file or assembly 'System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
16:47:41 : WakaTime : ERROR : An exception occured : Could not load file or assembly 'System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
10:34:41 : WakaTime : ERROR : An exception occured : Could not load file or assembly 'System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
10:44:03 : WakaTime : ERROR : An exception occured : Could not load file or assembly 'System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
10:44:16 : WakaTime : ERROR : Could not send heartbeat :  "C:\Users\KJ\AppData\Roaming\Notepad++\plugins\Config\wakatime-master\wakatime\cli.py" --key="" --file="new  0" --plugin="notepadpp/393293 notepadpp-wakatime/1.0.0"
10:44:16 : WakaTime : ERROR : Could not send heartbeat : Cannot start process because a file name has not been provided.
10:44:17 : WakaTime : ERROR : Could not send heartbeat :  "C:\Users\KJ\AppData\Roaming\Notepad++\plugins\Config\wakatime-master\wakatime\cli.py" --key="" --file="C:\TC\BIN\BEAT.CPP" --plugin="notepadpp/393293 notepadpp-wakatime/1.0.0"
10:44:17 : WakaTime : ERROR : Could not send heartbeat : Cannot start process because a file name has not been provided.
10:51:00 : WakaTime : ERROR : An exception occured : Could not load file or assembly 'System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.

please do check and let me know

**Comment by alanhamlett** [comment]
Can you check with the latest version of the plugin? Also, the log file has moved to `AppData\Roaming\Notepad++\plugins\config\WakaTime.log`.

**Comment by alanhamlett** [comment]
Closing as old.
