### ISSUE TITLE
v2.0.3 can't work normally

### ISSUE THREAD

**Issue by luojiedev** [wakatime/notepadpp-wakatime#11]
the log is:
[Wakatime Info 04:29:57 下午] Initializing WakaTime v2.0.3
[Wakatime HandledException 04:29:57 下午] Error initializing Wakatime: System.MissingMethodException: Method not found: 'IntPtr System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(!!0)'.
   at WakaTime.FuncItems.Add(FuncItem funcItem)
   at WakaTime.PluginBase.SetCommand(Int32 index, String commandName, NppFuncItemDelegate functionPointer, ShortcutKey shortcut, Boolean checkOnInit)
   at WakaTime.PluginBase.SetCommand(Int32 index, String commandName, NppFuncItemDelegate functionPointer, ShortcutKey shortcut)
   at WakaTime.WakaTime.CommandMenuInit()

**Comment by gandarez** [comment]
@l7l1l0l what's your OS?

**Comment by luojiedev** [comment]
@gandarez  Windows 7 (x64), Notepad++ v6.6.8

**Comment by luojiedev** [comment]
@gandarez What can I do for this Error?

**Comment by gandarez** [comment]
@l7l1l0l I can't reproduce this error here. I'm using Windows 8.1 (x64) and N++ v6.8.1
Would be better if I had a virtual machine running Windows 7.

**Comment by luojiedev** [comment]
Even if I update N++ to v6.8.3, the error again.
When I open N++, the error is "Missing "FuncItems" array, or the nb of Function Item is not set correctly ...".

**Comment by gandarez** [comment]
It'll be a tough one.

**Comment by luojiedev** [comment]
@gandarez What is the progress?

**Comment by antonio-rodrigues** [comment]
Using Notepad++ **v6.8.3** here, @ Windows 7 Enterprise x64 SP1 (Language: pt-PT).

Upon copy DLL to Plugins folder, the following error occurs at startup (extracted from AppData log):

"[Wakatime Info 09:06:17 ] Initializing WakaTime v2.0.3
[Wakatime HandledException 09:06:21 ] Error initializing Wakatime: System.MissingMethodException: Metodh not found: '**IntPtr** System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(!!0)'.
   em WakaTime.FuncItems.Add(FuncItem funcItem)
   em WakaTime.PluginBase.SetCommand(Int32 index, String commandName, NppFuncItemDelegate functionPointer, ShortcutKey shortcut, Boolean checkOnInit)
   em WakaTime.PluginBase.SetCommand(Int32 index, String commandName, NppFuncItemDelegate functionPointer, ShortcutKey shortcut)
   em WakaTime.WakaTime.**CommandMenuInit()**"

Any help, please?
Thank you.

**Comment by alanhamlett** [comment]
Is this fixed with the latest release v4.0.2?

**Comment by alanhamlett** [comment]
Closing unless we find it still occurring in the latest release.
