### ISSUE TITLE
Issue in Windows 10

### ISSUE THREAD

**Issue by pitchinnate** [wakatime/notepadpp-wakatime#12]
I have WakaTime installed and working with Netbeans correctly. However, I went to install it with Notepad++ and went though all the steps and I see in the WakaTime.log the following error:

[Wakatime Debug 10:12:09 AM] CLI STDERR: pythonw: can't open file 'C:\Users\Nathan\AppData\Roaming\Notepad++\plugins\Config\wakatime-master\wakatime\cli.py': [Errno 2] No such file or directory

I looked in that directory and there is no wakatime-master directory so I'm guessing whatever happens when Notepad++ runs the .dll it doesn't have the permissions to do it. I tried running Notepad++ as administrator and that didn't seem to help. Any ideas?

**Comment by alanhamlett** [comment]
Try manually unzipping wakatime-master into that location from here:

https://github.com/wakatime/wakatime/archive/master.zip

Can you check the folder properties of `Config` and see which users have write access? I was under the impression that AppData folders were writable by users to store settings in Windows, but I'm not sure of any edge cases.

**Comment by pitchinnate** [comment]
Manually putting these files in the directory worked. I still get a message in the log saying:

[Wakatime Debug 08:02:33 PM] CLI STDOUT: 
[Wakatime Debug 08:02:33 PM] CLI STDERR: 

But there error is blank and it is sending up data now.

As far as permissions go it seems as though all users have write access to:
C:\Users[USER]\AppData\Roaming\Notepad++\plugins

**Comment by alanhamlett** [comment]
@pitchinnate that output means everything is working and you have debug mode enabled. Turn off debug mode and the plugin will run faster and not output those `Debug` messages anymore.

**Comment by pitchinnate** [comment]
@alanhamlett awesome makes sense thanks for the help!

**Comment by condatek** [comment]
thanks it worked also in my wine setup were I was having the same issue.
