### ISSUE TITLE
Please create .zip release for Notepad++ Plugin Manager

### ISSUE THREAD

**Issue by bruderstein** [wakatime/notepadpp-wakatime#14]
Hi,

Plugin Manager for Notepad++ can only download .zip files at the moment. If you can create a zip release, then we can add this to PM.  I've had to remove it for now.

Cheers
Dave

**Comment by gandarez** [comment]
Thanks foir poiting this out @bruderstein 
I'll do it right now.

**Comment by gandarez** [comment]
@alanhamlett what happened with this discussion https://sourceforge.net/p/notepad-plus/discussion/482781/thread/691883f6/ ?

**Comment by alanhamlett** [comment]
@bruderstein we just use GitHub tags and upload a zip of the plugin? Is there a doc with more details? Thanks!

**Comment by bruderstein** [comment]
Thanks!  There just needs to be a zip version of the DLL to download. I was trying to publish, but there were no install steps for the plugin - if you look at the plugin now in the admin system (www.brotherstone.co.uk/npp/pm/admin), you can see the download step with your new .zip file, and the copy step to copy the extracted dll to the plugin directory (extraction of the zip happens automatically).  

If you update the version, when you update the download link, it asks you if you want the server to  download the zip to extract it, click yes, then you see the files in the zip on the right.  Next to the "wakatime.dll", is a "Add Hash" link, you need to verify that the MD5 matches your version, and click that "Add hash" link. That adds the md5 to a list of valid MD5s for executable code, and the "validate" tickbox on the copy step ensures that the downloaded and extracted wakatime.dll matches a hash that has been added.

I'm still working on a new system for this, but it's actually pretty easy once you've seen it.

Cheers
Dave.

**Comment by alanhamlett** [comment]
Thanks Dave! Just did this for v3.0.0. The available plugins are updated when Notepad++ next updates?

**Comment by alanhamlett** [comment]
@bruderstein there have been a few releases since Dec 2015 that fix major bugs, how often do you release new plugin versions once they are published on the admin page?
