### ISSUE TITLE
Doesn't work. WakaTime v2.0.3, Notepad++ v6.8

### ISSUE THREAD

**Issue by ttyk** [wakatime/notepadpp-wakatime#15]
Looks like plugin doesn't send any data. Client tooken is set correctly.

%AppData%\Roaming\Notepad++\plugins\config\WakaTime.log file:

http://puu.sh/lRnOS/f02fad52c8.log

OS: Windows 10 Enterprise
PS: There is no FireWall on WS, but there is IPTables on my main server, still they are not droping any requests.

**Comment by alanhamlett** [comment]
This line says it can't find [wakatime cli](https://github.com/wakatime/wakatime) so there must be a bug with downloading and extracting wakatime cli:
`CLI STDERR: C:\Py27\pythonw: can't open file 'C:\Users\ttyk\AppData\Roaming\Notepad++\plugins\Config\wakatime-master\wakatime\cli.py': [Errno 2] No such file or directory`

As a temporary fix, you could download [wakatime cli](https://github.com/wakatime/wakatime) and extract it to `C:\Users\ttyk\AppData\Roaming\Notepad++\plugins\Config`.

**Comment by ttyk** [comment]
Doesn't seems that it done anything.

I installed wakatime-master, restarted npp and writted couple files. Still no data.

In new log file:
[Wakatime Info 05:22:16 PM] Initializing WakaTime v2.0.3
[Wakatime Info 05:22:16 PM] Finished initializing WakaTime v2.0.3

**Comment by ttyk** [comment]
For some reason, after half a year i've got email from wakatime bot, and it seems that wakatime works fine now. My guess that my common version of python had fuckup HTTPS libs.

**Comment by alanhamlett** [comment]
Glad it's fixed!
