### ISSUE TITLE
Not compatible with laltest Notepad++ 6.9.2

### ISSUE THREAD

**Issue by ashishkp** [wakatime/notepadpp-wakatime#16]
Hi,

It seems Wakatime-Notpad++ plugin is not compatible with latest Notepad++ (6.9.2) version

Getting attached error. I am using Windows 7, 64 bit - i7 processor.

Thanks.
![waka_notepad_issue](https://cloud.githubusercontent.com/assets/2740259/17090396/c263eaee-524d-11e6-9ced-a069a5aa3f07.png)

**Comment by ghost** [comment]
I got this issue also from trying to download the .dll file directly to the plugins folder and making an empty xml file.  However, the Notepad++ plugin manager installation seems to work appropriately.

**Comment by ashishkp** [comment]
@gbhojraj  I already tried it initially, it was failing with below message.

---

Missing "FuncItems" array, or the nb of Function Item is not set correctly
This plugin is not compatible with current version of Notepad++.

Do you want to remove this plugin from plugins directory to prevent this message from the next launch time?

---

**Comment by alanhamlett** [comment]
Fixed with 83d0bb0741ebcc2b94117b1408d47dcca8fddd53 and released in v3.0.2.

**Comment by nelson6e65** [comment]
https://github.com/wakatime/notepadpp-wakatime/issues/13#issuecomment-241606957
