### ISSUE TITLE
Projects Not Grouping

### ISSUE THREAD

**Issue by VivaLaPanda** [wakatime/notepadpp-wakatime#18]
Everything I'm editing goes into a big Unknown Project, and I can't rename or delete that project. How can I select a specific project to have tracked time go towards?

**Comment by alanhamlett** [comment]
One of these ways, the easiest is using Git:
https://wakatime.com/help/getting-started/faq#set-project-name

**Comment by VivaLaPanda** [comment]
I'm editing files remotely via WinSCP, so it probably can't see my git repo. I'll just have to use the custom rules.
