### ISSUE TITLE
Not compatible with NPP v7 64-bit

### ISSUE THREAD

**Issue by geminorum** [wakatime/notepadpp-wakatime#19]

**Comment by guibranco** [comment]
Same problem!

**Comment by benyaminl** [comment]
Ah please wait lah, even the plugins manager for NPP 64 bit isn't officially supported...

**Comment by geminorum** [comment]
- the plugin manager is not an official NPP plugin and [has not been updated since 2012](https://github.com/bruderstein/nppPluginManager/releases) :)
- might help: [ Notepad++ plugin template (& plugin demo) x64 build available](https://notepad-plus-plus.org/community/topic/12053/notepad-plugin-template-plugin-demo-x64-build-available)

**Comment by alanhamlett** [comment]
@geminorum thanks, I'll look at upgrading this plugin to support x64 Notepad++ soon!

**Comment by benyaminl** [comment]
currently waiting :v:

**Comment by MaverickMartyn** [comment]
Bumping this too. :)

**Comment by chcg** [comment]
PM for x64, see https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.9
and the list therefore https://github.com/bruderstein/npp-plugins-x64

**Comment by turoni** [comment]
Is the x64 version available now?
I have installed the plugin manager but I don't find wakatime in the list.

**Comment by benyaminl** [comment]
@turoni wait a bit, if it's ready then it should be released.

**Comment by chcg** [comment]
@alanhamlett Any planning for a new release with x64?
@turoni Seems there is no release yet. For testing you could use the build result from https://ci.appveyor.com/project/chcg/notepadpp-wakatime/build/4.0.2.5/job/pjjapjvk2yfyre5u/artifacts until an official release is available.
