### ISSUE TITLE
[ASK]How WakaTimes recognize Project in NPP?

### ISSUE THREAD

**Issue by benyaminl** [wakatime/notepadpp-wakatime#20]
Ah, hello, I want to ask to @alanhamlett about project tracking, I use NPP alot for developing PHP, and NPP support categorizing project, nah until now WakaTime not record any data about the project and provide it with unknown project, anyway how I could make wakaTime recognize my project on NPP? Thanks

**Comment by alanhamlett** [comment]
The main way is using Git or other revision control, but it can also be manually configured with a `.wakatime-project` file in the project root folder or with a `[projectmap]` section in your `~/.wakatime.cfg` file:
https://wakatime.com/faq#set-project-name

**Comment by benyaminl** [comment]
@alanhamlett Ah sorry I haven't read the FAQ, thanks for that, sorry for disturbing with dumb question. Thanks
