### ISSUE TITLE
pythonw.exe error showed twice on start

### ISSUE THREAD

**Issue by lePouns** [wakatime/notepadpp-wakatime#23]
Hi !

Juste found your plugin and will absoluty test it but unfortunately, after installing and adding the key, everytime i start notepadd i got this pythonw.exe error `Application couldn't start correctly ...` I get this twice in a row on start, and several times after ..

Here is my debug conf

```
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPSvn.dll NppTextFX.dll PluginManager.dll regrexplace.dll SpellChecker.dll WakaTime.dll 
```

Thks
Gilles

**Comment by alanhamlett** [comment]
Just to make sure, can you open a cmd prompt and run this command:

`pythonw --version`

**Comment by lePouns** [comment]
Hi & thks for the response, here is the result of the cmd 
![image](https://user-images.githubusercontent.com/20596910/29674452-8c54f42a-88f2-11e7-94c0-bfd1ff02ee36.png)

Which means pythonw its not recognized ...

I used the plugin manager to install Wakatime

Thks
Gilles

**Comment by alanhamlett** [comment]
Can you download Python 3.6.2 and install with the default settings from this page:
https://www.python.org/downloads/

**Comment by lePouns** [comment]
Hello

Unfortunately, I can't install "Windows 7 Service Pack 1" which seems to be installed for Python

I've an old PC ...

Is there any other way to install Python without this Service Pack ?

Thks
Gilles

**Comment by alanhamlett** [comment]
You could try installing PyPy: https://pypy.org/download.html

**Comment by lePouns** [comment]
still the same error :(

**Comment by gandarez** [comment]
Is this still happening?
