### ISSUE TITLE
do not suppot X64

### ISSUE THREAD

**Issue by severalfly** [wakatime/notepadpp-wakatime#24]
hi, i am using X64 notepad++ which do not support X86 plugins now, would please update the plugins, thanks very much

**Comment by alanhamlett** [comment]
Could you try this version of the plugin, which has been updated to work with Notepad++ 64bit versions:
https://ci.appveyor.com/api/buildjobs/pjjapjvk2yfyre5u/artifacts/WakaTime.dll

**Comment by think2cat** [comment]
it's working fine
v7.5.3 64bit
thanks!

**Comment by nelson6e65** [comment]
This works. But... Why not included in releases?

**Comment by gandarez** [comment]
Released v4.1.0 https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.1.0

**Comment by alanhamlett** [comment]
Notepad++ x64bit support was added with #33, released in v4.1.0, and adding to the Plugins Admin list with notepad-plus-plus/nppPluginList#75.
