### ISSUE TITLE
Support for 32-bit version only

### ISSUE THREAD

**Issue by gtkpr** [wakatime/notepadpp-wakatime#25]
After having tried to install Waka myself, I noticed that there is support for only the 32-bit versions of Notepadd++.

**Comment by alanhamlett** [comment]
Does it work with this version of the plugin, which has been updated to work with Notepad++ 64bit versions:
https://ci.appveyor.com/api/buildjobs/pjjapjvk2yfyre5u/artifacts/WakaTime.dll

**Comment by gtkpr** [comment]
yes, it does. ty very much!

**Comment by mr-twady** [comment]
cannot load 32-bit plugin

**Comment by Phoenyx33** [comment]
https://ci.appveyor.com/api/buildjobs/pjjapjvk2yfyre5u/artifacts/WakaTime.dll does not exist any more and I still need a 64-bit wakatime for Notepad++. Is anyone working on this or is it being ignored?

**Comment by gandarez** [comment]
Released v4.1.0 https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.1.0

**Comment by alanhamlett** [comment]
Notepad++ x64bit support was added with #33.
