### ISSUE TITLE
Crashes Notepad++ v.7.51

### ISSUE THREAD

**Issue by auracool** [wakatime/notepadpp-wakatime#26]
After about 30 minutes or so i am having to restart notepad++ as wakatime crashes it. Once i remove wakatime plugin, notepad++ runs flawlessly. It's affecting productivity.

**Comment by gtkpr** [comment]
i've noticed a similar issue. not so much that it crashes, but rather it remains minimized and there's nothing i can do but close and reopen notepadd; so perhaps it is crashing. i wouldn't know :/

OS: Windows 10 64-bit version 1709

**Comment by gandarez** [comment]
Try updating to the latest version https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.1.0
