### ISSUE TITLE
Randomly freezes becomes unresponsive

### ISSUE THREAD

**Issue by gtkpr** [wakatime/notepadpp-wakatime#27]
i'm not sure if notepad is crashing or exactly what's going on, but for some reason notepad will in a sense become minimized and unresponsive. the only way to fix the issue is if i close and reopen it, which can cause massive issues if you don't regularly save your work...

**Windows 10 64-bit version 1709**
**Notepad version 7.5.1**

**Comment by ClearSeve** [comment]
官方都不处理一下吗?

**Comment by gandarez** [comment]
Try updating to the latest version https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.1.0
