### ISSUE TITLE
No log files created in Notepad++ 7.5.4 32 bit

### ISSUE THREAD

**Issue by gillespieza** [wakatime/notepadpp-wakatime#29]
I've got nothing - nothing being written to the logs at all. In fact, when I went to the directory the log file was meant to be in, there was no log at all. I created a blank file, hoping maybe it would work then, but nada.

If I type wakatime in the command line, I get an error - maybe the CLI is not being downloaded? 

I installed the plugin using the Plugin Manager. I tried running Notepad++ as administrator and reinstalling the Wakatime plugin, but nothing changed.

I'm running Windows 10 64-bit, with Notepad++ 7.5.4 32 bit, and the latest Plugin manager

**Comment by gillespieza** [comment]
I looked at the instructions for installing this plugin manually, and allowAppDataPlugins.xml was not created in the IDE root when I installed it using the Plugin Manager. I've created one now, but still nothing

**Comment by gandarez** [comment]
Try updating to the latest version https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.1.0
