### ISSUE TITLE
Error: Unknown Exception

### ISSUE THREAD

**Issue by vandai** [wakatime/notepadpp-wakatime#3]
After installing, i always got error box: "Unknown Exception" when launching notepad++.
Also, it taking so long to notepad++ to start after i clicked it.

**Comment by gandarez** [comment]
What's your notepad++' version?

**Comment by alanhamlett** [comment]
Do you have any error messages in `AppData\Roaming\Notepad++\plugins\config\WakaTime.log`?

**Comment by alanhamlett** [comment]
Closing as old.
