### ISSUE TITLE
Doesn't Work with Notepad++ V7.5.8 (64-Bit)

### ISSUE THREAD

**Issue by Chookees** [wakatime/notepadpp-wakatime#30]

**Comment by jnickle** [comment]
same issue. doesn't work with 64 bit version.  any fix?

**Comment by auracool** [comment]
Come on team we need an update on this fix

**Comment by gandarez** [comment]
Released v4.1.0 https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.1.0

**Comment by alanhamlett** [comment]
Notepad++ x64bit support was added with #33.
