### ISSUE TITLE
Doesn't Work with Notepad++ V7.6.0 (32-Bit)

### ISSUE THREAD

**Issue by bulusite** [wakatime/notepadpp-wakatime#31]
Doesn't Work with Notepad++ V7.6.0 (32-Bit)

**Comment by huzhangzheng** [comment]
Doesn't Work with Notepad++ V7.6.0 (64-Bit)

**Comment by F50Ci37Y** [comment]
Doesn't Work with Notepad++ V7.6.2 (64-Bit)
i copy dll , but notepad++ not found it.

**Comment by gandarez** [comment]
Released v4.1.0 https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.1.0

**Comment by alanhamlett** [comment]
Notepad++ x64bit support was added with #33
