### ISSUE TITLE
Doesn't Work with Notepad++ V7.6.3 (64-Bit)

### ISSUE THREAD

**Issue by MenukaIshan** [wakatime/notepadpp-wakatime#32]
My OS is Windows 10 Home 64 bit. with above notepad++ version.
Followed the documented procedures but the plugin doesn't seem to work 
If Need additional details please ask.

**Comment by Phoenyx33** [comment]
Ok, wakatime, I need an answer; is there going to be a notepadpp x64 plugin or not. If not, I'm moving to vscode and probably a different time usage plugin.

**Comment by tb-mtg** [comment]
Does not work for me either

**Comment by henriqueap** [comment]
Me too! I'm waiting a 64 bit version, please!

**Comment by Kingong** [comment]
me too.

**Comment by luayua** [comment]
Me too, don't work with Notepad++ V7.6.3 (64-Bit)  Windos7.

**Comment by think2cat** [comment]
Dont't support notepad++ x64 version

**Comment by tb-mtg** [comment]
Issued also raised here: https://github.com/wakatime/wakatime/issues/168 as no issues have been closed here since May-2017 by the looks of it.

**Comment by gandarez** [comment]
Released v4.1.0 https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.1.0

**Comment by alanhamlett** [comment]
Notepad++ x64bit support was added with #33.
