### ISSUE TITLE
Plugin does not work with Notepad++ v7.8.9 and does not generate log file

### ISSUE THREAD

**Issue by agoodshort** [wakatime/notepadpp-wakatime#37]
**Description of the issue**
Not 100% sure the version on Notepad++ is really the reason of this issue. But Notepad++ does not generate log files but it properly configured. VS Code from the same machine is able to submit with no issues.

**Steps to reproduce**
- Install Notepad++ v7.8.9
- Install WakaTime via Plugins admin
- Configure and restart Notepad++
- Log fill in `C:\Users\<user>\AppData\Roaming\Notepad++\plugins\config\WakaTime.log` does not get generated

**Steps tested so far**
- Re-install Notepad++
- Re-install WakaTime via Plugins Admin
- Run Notepad++ as administrator

**Comment by nmambre** [comment]
I'm having the same issue. 
Just to add Notepad++ v7.8.9 64bit version and allowAppDataPlugins.xml created in C:\Program Files\Notepad++ directory

**Comment by erickksun** [comment]
The same.
win10  2004  7.9  x64

**Comment by gandarez** [comment]
A new version has been released to fix all problems discussed in this thread. It's tested for `x86 v7.6.6` and `x64 v7.9`. You can manually download it from [Releases](https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.2.0) or wait until this [PR](https://github.com/notepad-plus-plus/nppPluginList/pull/237) gets approved and then you can download using Plugins Admin.

**Comment by Jasonnor** [comment]
@gandarez Hi, I try new release version (x64, 4.2) in notepad++ `x64 v7.9` and (x86 4.2) version in notepad++ `x86 v7.6.6`, but still does not work.
Also no wakatime log file in `AppData\Roaming\Notepad++\plugins\config`, and no status recorded in https://wakatime.com/plugins/status
Can you take a look on it? Thanks!

**Comment by gandarez** [comment]
@Jasonnor you can make a call to our endpoint and double check all editors from today's coding. Using postman or any other related software make a `GET` to `https://api.wakatime.com/api/v1/users/current/summaries?start=today&end=today` and set the `Authorization` header with the value `Basic <api_key_base_64_encoded>`.

**Comment by Jasonnor** [comment]
@gandarez Thank you for your assistance, but the `editors` in API response does not include Notepad++.
I tested both VS Code and GoLand with its WakaTime plugins and both were recorded in the GET response.
```json
            "editors": [
                {
                    "digital": "0:00:57",
                    "hours": 0,
                    "minutes": 0,
                    "name": "VS Code",
                    "percent": 51.01,
                    "seconds": 57,
                    "text": "57 secs",
                    "total_seconds": 57.300374
                },
                {
                    "digital": "0:00:55",
                    "hours": 0,
                    "minutes": 0,
                    "name": "GoLand",
                    "percent": 48.99,
                    "seconds": 55,
                    "text": "55 secs",
                    "total_seconds": 55.033
                }
            ],
```
Is there any possibility to view the log of notepad++ wakatime plugin except `AppData\Roaming\Notepad++\plugins\config`? Thank you!

**Comment by gandarez** [comment]
The log file is created at `C:\Users\{user}\AppData\Roaming\WakaTime\WakaTime.log`

**Comment by Jasonnor** [comment]
I got the following error message:
```
[Wakatime Info 10:33:48] Initializing WakaTime v4.2.0
[Wakatime HandledException 10:33:48] Are you behind a proxy? Try setting a proxy in WakaTime Settings with format https://user:pass@host:port. Exception Traceback:: 
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at WakaTime.Dependencies.DownloadAndInstallCli()
   at WakaTime.WakaTimePackage.InitializeAsync()
[Wakatime Info 10:33:48] Finished initializing WakaTime v4.2.0
```
Even though I did not set proxy(and my network is not behind a proxy)... 
I don’t know if I’m the only one encountering this problem 😅

**Comment by gandarez** [comment]
There's a new version `4.2.1` that will fix the problem you've gotten. So please download it from here and replace in the plugin's directory. https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.2.1

**Comment by Jasonnor** [comment]
Hi @gandarez , I got same error as `4.2.0` after upgrade to `4.2.1`
Here's log: (BTW I have opened debug mode to see debug log)
```
[Wakatime Info 09:45:44] Initializing WakaTime v4.2.1
[Wakatime Debug 09:45:44] Python found by Fixed Path: \python27\pythonw
[Wakatime Debug 09:45:44] Downloading wakatime-cli...
[Wakatime Debug 09:45:44] No proxy will be used. It's either not set or badly formatted.
[Wakatime HandledException 09:45:44] Are you behind a proxy? Try setting a proxy in WakaTime Settings with format https://user:pass@host:port. Exception Traceback:: 
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at WakaTime.Dependencies.DownloadAndInstallCli()
   at WakaTime.WakaTimePackage.InitializeAsync()
[Wakatime Info 09:45:44] Finished initializing WakaTime v4.2.1
```
And notepad++ not display in response of `/api/v1/users/current/summaries`.
Please let me know if there is anything I can help, thanks!

**Comment by gandarez** [comment]
Sorry for the time spent as I can't reproduce your scenario here. There are two step for downloading and the version `4.2.2` has fixed the second one which is the download for the client. 

https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.2.2

**Comment by Jasonnor** [comment]
It's now working perfectly! Thank you very much 😄

**Comment by nmambre** [comment]
Also saw a pulse on my dashboard, seems to be working.

**Comment by agoodshort** [comment]
Recently updated to Notepad++ v7.9 and since then I have no more issues. Still using WakaTime 4.1

**Comment by gandarez** [comment]
Thanks for the feedback given.

**Comment by bulletproof2k** [comment]
WakaTime the plugin does not work for me, usage statistics are not displayed on WakaTime dashboard (Version: 4.2.3.0) 🤷‍♂️

![1650919043043-screenshot_7](https://user-images.githubusercontent.com/1818579/165174550-6f38564e-6292-487f-957e-af894750c602.jpg)
