### ISSUE TITLE
wanted compatibililty for Notepad++ v7.9.1

### ISSUE THREAD

**Issue by NirmalSilwal** [wakatime/notepadpp-wakatime#41]
Hi there, I tried to integrate wakatime in latest version of wakatime. I tried as suggested in [this site of wakatime](https://wakatime.com/notepad++). I updated the Notepad++ to latest version of 7.9.1 as of today.

I got the below error later.

![waka time issue](https://user-images.githubusercontent.com/31946761/104956690-a62f2f80-59f2-11eb-90e0-6aa177c68126.PNG)

I request for adding this compatibility in latest version of Notepad++ also.

What do you think of the idea? Do let me know if you have any suggestions for me.

Best
Nirmal

**Comment by ghost** [comment]
WakaTime is working in my Notepad++ v7.9.1. It looks like you are trying to use incompatible version of WakaTime with your Notepad++. Your Notepad++ is x86 (32-bit) version and you trying to run 64-bit version of WakaTime. Try to use WakaTime x86 version.

**Comment by NirmalSilwal** [comment]
okay, I will try that combination.

Thank you @lenka-bendova for the suggestion.

**Comment by NirmalSilwal** [comment]
It worked. Thanks
