### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by darhanger** [wakatime/notepadpp-wakatime#42]
Install plugin for np++ also for MS word. But seems its not grab anything.

**Comment by gandarez** [comment]
Hi @darhanger,

Is this problem still happening?

**Comment by mrepol742** [comment]
Same issue here. I install np++ and wakatime plugin but it didnt work even tho i used np++ for an hour. My dashboard and plugin status aren't showing anything related to np++. and i can see any window or view that counts the hours i coded like in android studio and atom which is placed in bottom right corner.

**Comment by darhanger** [comment]
> Hi @darhanger,
> 
> Is this problem still happening?

For now its come back. 2-3 days ago its stop checking data. From notepad++ and other IDE

**Comment by alanhamlett** [comment]
Should be fixed with v4.2.3?
