### ISSUE TITLE
Not tracking time, no errors in wakatime.log file

### ISSUE THREAD

**Issue by darhanger** [wakatime/notepadpp-wakatime#44]
More then week ago Waka stop grab data.

![image](https://user-images.githubusercontent.com/22445395/138215230-e20f9a21-29b8-4ec8-aadd-62289a2e6296.png)

Even browser plugin not take data.

**Comment by darhanger** [comment]
@alanhamlett

**Comment by alanhamlett** [comment]
Can you try re-installing the extension for Notepad++?

**Comment by darhanger** [comment]
@alanhamlett reinstal it few times. Same stuff

**Comment by alanhamlett** [comment]
Do you have a `WakaTime.log` file located here:
https://github.com/wakatime/notepadpp-wakatime#troubleshooting

**Comment by darhanger** [comment]
@alanhamlett 

![image](https://user-images.githubusercontent.com/22445395/138672582-0e5dcf2f-d310-4055-b3ff-36b6901bcf4e.png)

**Comment by gandarez** [comment]
Maybe the language's system can be a point to be considered.

**Comment by darhanger** [comment]
@gandarez its work before. Then stop. So problem not in language.

**Comment by darhanger** [comment]
@alanhamlett so. No fix? or?

**Comment by darhanger** [comment]
so. How long time w8?

**Comment by alanhamlett** [comment]
Fixed with v4.2.3.
