### ISSUE TITLE
5.0.1 not in Plugins Admin

### ISSUE THREAD

**Issue by modem7** [wakatime/notepadpp-wakatime#49]
Heya, 

The latest version in Plugins Admin in N++ seems to be 4.2.3, and it hasn't seemed to have picked up the latest version. 

https://github.com/notepad-plus-plus/nppPluginList/blob/master/doc/plugin_list_x64.md

Unsure if this is a bug or intended as with discussions in https://github.com/wakatime/notepadpp-wakatime/issues/46.

Thanks!

**Comment by modem7** [comment]
Going off the back of https://github.com/wakatime/notepadpp-wakatime/pull/51 and the 5.0.0 release, a PR will need to be raised when it's ready.

**Comment by gandarez** [comment]
` v5.0.1`  has been released and we are waiting this PR to get merged
https://github.com/notepad-plus-plus/nppPluginList/pull/537

**Comment by alanhamlett** [comment]
The PR to the plugins list repo was merged!

**Comment by alanhamlett** [comment]
Leaving open because even though the PR was merged, the plugin list hasn't been distributed yet so it's not yet updated to 5.0.1:
https://github.com/notepad-plus-plus/nppPluginList/blob/master/doc/plugin_list_x64.md

**Comment by alanhamlett** [comment]
v5.0.1 is now available in the plugins admin. You still need to remove the `waka_` prefix from your api key until v5.1.0 is released.
