### ISSUE TITLE
notepad++ slow to start

### ISSUE THREAD

**Issue by KeNJiKunG** [wakatime/notepadpp-wakatime#5]
After I install the plugin, notepad++ will take about 10-20 seconds before the main editor will appear. And after I remove the plugins, the editor display in 1 or 2 sec.

**Comment by alanhamlett** [comment]
By project, you mean an atom [Project Directory](https://atom.io/docs/api/v1.0.4/Project#instance-getDirectories) from the `Add Project Folder` menu item?

**Comment by alanhamlett** [comment]
Can you check the latest release v2.0.1 of the plugin?

3572b5d8a424b84d52eda91e188f3cbf1860ff28 should have fixed the slow startup.

**Comment by KeNJiKunG** [comment]
The issue is gone after I update the plugin to v2.0.1.

Thank you very much.
