### ISSUE TITLE
Please enter valid API key

### ISSUE THREAD

**Issue by modem7** [wakatime/notepadpp-wakatime#53]
When trying to enter the API key (either with or without the "waka_" prefix), the following message comes up.

![image](https://user-images.githubusercontent.com/4349962/211453779-e827612c-9180-4730-9bd8-9dffbb8e4380.png)

It looks like the field only accepts 36 characters, and the full API key is 41 characters.

notepadpp-wakatime version: 5.1.0
np++ version: 8.4.8
Windows 10

**Comment by modem7** [comment]
@alanhamlett - Looking further at your comment in https://github.com/wakatime/notepadpp-wakatime/issues/49#issuecomment-1374583026, is 5.0.2 superseded by 5.1.0? If so, the issue still is not resolved, unfortunately.

**Comment by alanhamlett** [comment]
Yes, that was a typo. The latest release is 5.1.0 but it's not available in the plugin admin menu yet. You can try it manually by extracting the release's DLL into your plugins folder.

**Comment by modem7** [comment]
> Yes, that was a typo. The latest release is 5.1.0 but it's not available in the plugin admin menu yet. You can try it manually by extracting the release's DLL into your plugins folder.

Sweet, thought as much, but wanted to double check! 

Aye, I've done that, but unfortunately the issue above with the character limit is present.

**Comment by alanhamlett** [comment]
Oops, fixed with cbe13eb7169f549fa926616a8dd6c1bbc2956b96.
