### ISSUE TITLE
API keys with the "waka_" prefix are not accepted

### ISSUE THREAD

**Issue by DavoDC** [wakatime/notepadpp-wakatime#54]
The WakaTime plugin for Notepad++ does not accept API keys with the "waka_" prefix.
If you try to enter an API key with the "waka_" prefix, it says "Please enter valid Api Key".
However  https://wakatime.com/api-key  displays keys with this prefix.

**Comment by alanhamlett** [comment]
Is your WakaTime plugin version 5.1.1? That latest version should accept keys with the `waka_` prefix already:

800a388ce7f73ee45ee847f5a6d3cadc097163f9

**Comment by DavoDC** [comment]
Thank you for your prompt reply! 🙂 Sorry, you're right. 
I was on an older version (5.0.1). After updating (manually), it accepted the prefixed key. So no problem!

I assumed because I just got it today from the inbuilt Plugins Admin that it was the newest version, but it turns that it still provides an older version for some reason. 
**Update:** I think it was an outdated 32-bit version of Notepad++. Upgraded to newest 64-bit version, and then 5.1.1 could be installed via the Plugins Admin 👍
