### ISSUE TITLE
Extension causes notepad++ to freeze

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/notepadpp-wakatime#57]
> Using this extension causes notepad++ to freeze

_Originally posted by @ola-pt in https://github.com/wakatime/notepadpp-wakatime/issues/56#issuecomment-1612456626_

**Comment by alanhamlett** [comment]
@ola-pt can you describe when it freezes in a lot of detail? Here's some helpful questions:

1. Does it freeze on startup or while typing in files?
2. Does it only freeze for some seconds then un-freeze, or do you have to kill Notepad++ because it never un-freezes?

**Comment by ClearSeve** [comment]
same issues

**Comment by alanhamlett** [comment]
@ClearSeve does it freeze on startup, while typing, or just randomly? Does it freeze temporarily and then un-freeze after some time, or just freeze forever until Notepad++ is killed?

**Comment by alanhamlett** [comment]
Make sure you're using the latest version (5.1.1). Closing this for now, until the requested info provided.
