### ISSUE TITLE
Add support fo wakatime plugin in Linux version of Notepad++

### ISSUE THREAD

**Issue by RyanZurrin** [wakatime/notepadpp-wakatime#58]
I was just wondering if there will ever be support for the Wakatime plugin for the Linux version of Notepad++.

**Comment by gandarez** [comment]
Notepad++ does not support Linux.

**Comment by alanhamlett** [comment]
@RyanZurrin using this snap package? https://itsfoss.com/notepad-plus-plus-linux/

Shouldn't it just work without changes?
