### ISSUE TITLE
notepad++ 7.9.0 not working log file has error，don‘t no what's mean

### ISSUE THREAD

**Issue by jeffxjh** [wakatime/notepadpp-wakatime#59]
```{"now": "2021/05/13 16:20:11 +0800", "version": "13.1.0", "plugin": "notepadpp/458845 notepadpp-wakatime/4.2.2", "time": 1620894004.489945, "caller": "C:\\Users\\xxxxx\\AppData\\Roaming\\WakaTime\\wakatime-master\\wakatime\\logger.py", "lineno": 62, "file": "C:\\Users\\xxxxx\\Desktop\\\u65b0\u5efa\u6587\u4ef6\u5939 (3)\\new 1.txt", "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\xxxxx\\AppData\\Roaming\\WakaTime\\wakatime-master\\wakatime\\main.py\", line 66, in execute\n    hb = Heartbeat(vars(args), args, configs)\n  File \"C:\\Users\\xxxxx\\AppData\\Roaming\\WakaTime\\wakatime-master\\wakatime\\heartbeat.py\", line 109, in __init__\n    project, branch = get_project_info(configs, self, data)\n  File \"C:\\Users\\xxxxx\\AppData\\Roaming\\WakaTime\\wakatime-master\\wakatime\\project.py\", line 92, in get_project_info\n    project_file = os.path.join(project.folder(), '.wakatime-project')\n  File \"C:\\Users\\xxxxx\\AppData\\Roaming\\WakaTime\\wakatime-master\\wakatime\\projects\\subversion.py\", line 45, in folder\n    if 'Repository Root' not in self.info:\nAttributeError: 'Subversion' object has no attribute 'info'\n"}```

**Comment by alanhamlett** [comment]
This is from an old version  of the notepadpp-wakatime plugin, back when it used the [legacy python cli](https://github.com/wakatime/legacy-python-cli). Now that notepadpp-wakatime uses the new wakatime-cli, this bug should be fixed.
