### ISSUE TITLE
Startup time increased after installing

### ISSUE THREAD

**Issue by Rychard** [wakatime/notepadpp-wakatime#6]
With the plugin installed to Notepad++, I've noticed that it takes a few seconds for the application to start.  Without the plugin installed, the startup time of Notepad++ is nearly instantaneous.

**Comment by gandarez** [comment]
Pull Request #8

**Comment by dvmarcilio** [comment]
I'm also experiencing increased startup time. But in my case it's taking almost a minute more to start.
Using v2.0.2 with Notepad++ v.6.82

**Comment by gandarez** [comment]
@dvmarcilio We're figuring out what's making startup slower in some machines

**Comment by alanhamlett** [comment]
@dvmarcilio is this every time you start Notepad++ or just the first time?

**Comment by dvmarcilio** [comment]
@alanhamlett this happens every time I start Notepad++.

**Comment by dvmarcilio** [comment]
@gandarez @alanhamlett just to confirm that it no longer happens with v2.0.3. Thank you for the fast response.
