### ISSUE TITLE
"Please enter valid Api Key." problem

### ISSUE THREAD

**Issue by adib-yg** [wakatime/notepadpp-wakatime#61]
I copy my api key from wakatime settings and paste it in input but it says "Please enter valid Api key."

My api key is 41 characters.

<img src="https://i.ibb.co/jDBzJfw/Screenshot-249.png" alt="Screenshot">

**Comment by adib-yg** [comment]
I find out that the installed version is 4.2.3
I manually upgraded to 5.1.1 and it was solved.
WakaTime should be upgraded in the plugin manager.

**Comment by alanhamlett** [comment]
Must be a bug in Notepad++ Plugin Manager, because the version listed on their repo points to 5.1.1.
