### ISSUE TITLE
Downloads ~2.5MB every time Notepad++ is launched

### ISSUE THREAD

**Issue by Rychard** [wakatime/notepadpp-wakatime#7]
Each time Notepad++ is launched, a web request is made to the following URL:

[`https://codeload.github.com/wakatime/wakatime/zip/master`](https://codeload.github.com/wakatime/wakatime/zip/master)

This seems unnecessary to do _every_ time the application is started.  If it's just pulling down some code, ideally it would cache this data locally and retrieve it only when it differs from the latest version on Github.

Is this perhaps the underlying cause for #6?

**Edit:** After briefly looking at the code, it seems that it's _supposed_ to cache this data, and only retrieve it [when it doesn't exist](https://github.com/wakatime/notepadpp-wakatime/blob/master/WakaTime/WakaTime.cs#L58).  

The conditional calls `DoesCliExist()` as well as `IsCliLatestVersion()`.

The code for `DoesCliExist()` is relied on elsewhere (or else the plugin wouldn't work at all, from what I can tell), so it seems somewhat safe to assume that the bug isn't in that method.

Having not looked into it much further than this, the code for `IsCliLatestVersion()` seems to be erroneously returning `false`.  the issue may have something to do with [this conditional](https://github.com/wakatime/notepadpp-wakatime/blob/master/WakaTime/WakaTime.cs#L270), but without actually debugging it, I can't be certain.

For what it's worth, here's the output of the roughly equivalent command entered directly into the command prompt.

```
C:\Users\Joshua>python "C:\Users\Joshua\AppData\Roaming\Notepad++\plugins\config\wakatime-master\wakatime\cli.py" --version
4.1.0
```

Which, at a glance, seems to match the [constant defined in that file](https://github.com/wakatime/notepadpp-wakatime/blob/master/WakaTime/WakaTime.cs#L19).

**Comment by gandarez** [comment]
I'm gonna take a look into this problem.

**Comment by alanhamlett** [comment]
Thank you @gandarez, this has been puzzling me for a while with IntelliJ on Windows too.

**Comment by gandarez** [comment]
Pull Request #8
